=== robvik/xml-xslt-xquery-to-html/schema.xsd
<!--
		Author: Robin Viktorsson
		Date:	2017-11-02
		Filename: schema.xsd
	-->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="allchannels">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tv" type="tvType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="tvType">
    <xs:sequence>
      <xs:element name="programme" type="programmeType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="channel"/>
    <xs:attribute type="xs:string" name="logo"/>
  </xs:complexType>

  <xs:complexType name="programmeType">
    <xs:sequence>
	  <xs:element type="xs:string" name="id"/>
      <xs:element type="xs:string" name="title"/>
      <xs:element type="xs:string" name="desc" minOccurs="0"/>
      <xs:element type="xs:string" name="start"/>
      <xs:element type="xs:string" name="stop"/>
      <xs:element type="xs:short" name="date" minOccurs="0"/>
	  <xs:element type="xs:string" name="type" minOccurs="0"/>
      <xs:element type="xs:string" name="category" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== robvik/xml-xslt-xquery-to-html/xml_docs/allChannels.xml
<?xml version="1.0" encoding="UTF-8"?>
<allchannels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../schema.xsd">
	<tv channel="svt1.svt.se" logo="svt1.svt.se.png">
		<programme>
			<id>idelem4x3</id>
			<title>Sverige idag</title>
			<desc>Nyheter från hela Sverige - direkt från Umeå.</desc>
			<start>04:45</start>
			<stop>05:15</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
		<programme>
			<id>idelem4x33</id>
			<title>Go'kväll</title>
			<desc>Intervju med Emma Frans, doktor i medicinsk epidemiologi, som vill slå hål på myter och få oss att förstå att vi måste lita mer på vetenskap och forskning. En tittare får ny stil av stylisterna Eva-Lena Rylander och Hulda Andersson. Reportage om Ingrid Ölund som bakar ett prisat barkbröd. Programledare Beppe Starbrink.</desc>
			<start>05:15</start>
			<stop>06:00</stop>
			<date>2017</date>
			<type>series</type>
			<category>Magazine</category>
		</programme>
		<programme>
			<id>idelem4x69</id>
			<title>Morgonstudion</title>
			<desc>Dagens viktigaste nyheter och analyser med ständiga uppdateringar. Vi sänder direkt inrikes- och utrikesnyheter inklusive sport, kultur och nöje. Dessutom intervjuer med aktuella gäster. Nyhetssammanfattningar varje kvart med start kl 06.00. Lokala nyheter från kl 07.05. Väder kvart i och kvart över. Läs text-tv sid 679.</desc>
			<start>06:00</start>
			<stop>06:15</stop>
			<date>2017</date>
			<type>series</type>
			<category>Politics</category>
			<category>Society</category>
		</programme>
		<programme>
			<id>idelem4x102</id>
			<title>Go'kväll</title>
			<desc>Intervju med Emma Frans, doktor i medicinsk epidemiologi, som vill slå hål på myter och få oss att förstå att vi måste lita mer på vetenskap och forskning. En tittare får ny stil av stylisterna Eva-Lena Rylander och Hulda Andersson. Reportage om Ingrid Ölund som bakar ett prisat barkbröd. Programledare Beppe Starbrink.</desc>
			<start>09:10</start>
			<stop>09:55</stop>
			<date>2017</date>
			<type>series</type>
			<category>Magazine</category>
		</programme>
		<programme>
			<id>idelem4x138</id>
			<title>Anslagstavlan</title>
			<start>09:55</start>
			<stop>10:00</stop>
			<date>2017</date>
			<type>series</type>
		</programme>
		<programme>
			<id>idelem4x162</id>
			<title>Engelska Antikrundan</title>
			<desc>Tusentals besökare väntar ivrigt med sina föremål när Antikrundan är tillbaka vid universitetet i Stowe, Buckinghamshire. En av besökarna är den flerfaldige formel 1-världsmästaren Jackie Stewart som har med sig en oväntad trofé.</desc>
			<start>10:00</start>
			<stop>11:00</stop>
			<date>1979</date>
			<type>series</type>
			<category>Documentary</category>
			<category>Special Interest</category>
		</programme>
		<programme>
			<id>idelem4x204</id>
			<title>Ishockey</title>
			<desc>Den 58:e upplagan av TV-pucken avgörs i Göteborg och dagens kvartsfinaler spelas i Frölundaborg. Experter: Mikael Renberg och Jonas Andersson.</desc>
			<start>11:00</start>
			<stop>17:55</stop>
			<date>2017</date>
			<type>series</type>
			<category>Hockey</category>
		</programme>
		<programme>
			<id>idelem4x246</id>
			<title>Sverigeresan</title>
			<desc>"Alla känner en Arne". Det vore närmast tjänstefel att göra en resa genom idrotts-Sverige utan att beröra hjärtat: eldsjälarna. Därför ska vi till tre orter, tre föreningar - för att upptäcka platsens betydelse, gemenskap och passion. Reportageserie om idrotts-Sverige bortanför de stora arenorna.</desc>
			<start>17:55</start>
			<stop>18:00</stop>
			<date>2017</date>
			<type>sports</type>
			<category>Sports</category>
		</programme>
		<programme>
			<id>idelem4x276</id>
			<title>Rapport</title>
			<start>18:00</start>
			<stop>18:13</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
		<programme>
			<id>idelem4x297</id>
			<title>Kulturnyheterna</title>
			<start>18:13</start>
			<stop>18:25</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
		<programme>
			<id>idelem4x318</id>
			<title>Sportnytt</title>
			<start>18:25</start>
			<stop>18:30</stop>
			<date>2017</date>
			<type>sports</type>
			<category>Sports</category>
		</programme>
		<programme>
			<id>idelem4x339</id>
			<title>Lokala nyheter</title>
			<start>18:30</start>
			<stop>18:45</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
		<programme>
			<id>idelem4x366</id>
			<title>Go'kväll</title>
			<desc>Arkitekten Gert Wingårdh bjuder till bords. Sissel Kyrkjebø står på musikscenen. Biorecensioner med Göran Everdahl.</desc>
			<start>18:45</start>
			<stop>19:30</stop>
			<date>2017</date>
			<type>series</type>
			<category>Magazine</category>
		</programme>
		<programme>
			<id>idelem4x408</id>
			<title>Rapport</title>
			<start>19:30</start>
			<stop>19:55</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
		<programme>
			<id>idelem4x429</id>
			<title>Lokala nyheter</title>
			<start>19:55</start>
			<stop>20:00</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
		<programme>
			<id>idelem4x456</id>
			<title>Doobidoo</title>
			<desc>Lekfullt musik- och frågesportprogram under ledning av Lasse Kronér. I kvällens avsnitt tävlar Björn Kjellman och Lilla Namo mot Pia Johansson och Edward af Sillén.</desc>
			<start>20:00</start>
			<stop>21:00</stop>
			<date>2017</date>
			<type>series</type>
			<category>Music</category>
		</programme>
		<programme>
			<id>idelem4x486</id>
			<title>Skavlan</title>
			<start>21:00</start>
			<stop>22:00</stop>
			<date>2017</date>
			<type>series</type>
			<category>Documentary</category>
			<category>Entertainment</category>
		</programme>
		<programme>
			<id>idelem4x516</id>
			<title>Grotescos sju mästerverk</title>
			<desc>Flyktingkrisen - en musikal. En musikal om Sverige och en period i vår nutidshistoria som markerade en kraftig kursändring i svensk politik. Grotesco har tonsatt perioden juni-november 2015, då Sverige tog emot fler asylsökande än någonsin till följd av kriget i Syrien och andra konflikter.</desc>
			<start>22:00</start>
			<stop>22:30</stop>
			<date>2015</date>
			<type>series</type>
			<category>Comedy</category>
		</programme>
		<programme>
			<id>idelem4x585</id>
			<title>Släng dig i brunnen</title>
			<desc>Standup med några av Sveriges bästa ståuppkomiker. Inspelat på Norra Brunn i Stockholm.</desc>
			<start>22:30</start>
			<stop>22:45</stop>
			<date>2017</date>
			<type>series</type>
			<category>Comedy</category>
		</programme>
		<programme>
			<id>idelem4x642</id>
			<title>American odyssey</title>
			<desc>Odelle, Aslam och Luc måste fatta ett beslut angående Frank, som nu är i deras förvar.</desc>
			<start>22:45</start>
			<stop>23:30</stop>
			<date>2015</date>
			<type>series</type>
			<category>Series</category>
		</programme>
		<programme>
			<id>idelem4x693</id>
			<title>SVT Nyheter</title>
			<start>23:30</start>
			<stop>23:35</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
		<programme>
			<id>idelem4x720</id>
			<title>Sverige idag</title>
			<desc>Nyheter från hela Sverige - direkt från Umeå.</desc>
			<start>23:35</start>
			<stop>23:50</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
		<programme>
			<id>idelem4x750</id>
			<title>Jordskott</title>
			<desc>Jakten på den försvunna flickan Robin fortsätter och Evas situation kompliceras av det oväntade ansvaret för den förrymda Kalem. Eva och Wass gräver djupare i utredningen och hittar något som för länge sedan tillhört Evas mamma. Bahar blir allt mer misstänksam mot Eva och Wass beteende. I jakten på den skyldiga gräver Eva och Wass fram bevis på att den de letar efter mördat många gånger förut. Tom dras samtidigt in i en utredning av en bestialisk björnattack i Silverhöjd som väcker intresse från oväntat håll.</desc>
			<start>23:50</start>
			<stop>00:50</stop>
			<date>2015</date>
			<type>series</type>
			<category>Drama</category>
		</programme>
	</tv>
	<tv channel="svt2.svt.se" logo="svt2.svt.se.png">
		<programme>
			<id>idelem5x3</id>
			<title>SVT Nyheter</title>
			<start>01:00</start>
			<stop>01:05</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
		<programme>
			<id>idelem5x30</id>
			<title>Sportnytt</title>
			<start>01:05</start>
			<stop>01:25</stop>
			<date>2017</date>
			<type>sports</type>
			<category>Sports</category>
		</programme>
		<programme>
			<id>idelem5x51</id>
			<title>Nyhetstecken</title>
			<desc>Nyheter på teckenspråk.</desc>
			<start>01:25</start>
			<stop>01:35</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
		<programme>
			<id>idelem5x75</id>
			<title>SVT Nyheter</title>
			<start>02:00</start>
			<stop>02:05</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
		<programme>
			<id>idelem5x102</id>
			<title>Sverige idag</title>
			<desc>Nyheter från hela Sverige - direkt från Umeå.</desc>
			<start>02:05</start>
			<stop>02:35</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
		<programme>
			<id>idelem5x132</id>
			<title>SVT Nyheter</title>
			<start>03:00</start>
			<stop>03:05</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
		<programme>
			<id>idelem5x159</id>
			<title>SVT Nyheter</title>
			<start>04:00</start>
			<stop>04:05</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
		<programme>
			<id>idelem5x186</id>
			<title>SVT Nyheter</title>
			<start>05:00</start>
			<stop>05:05</stop>
			<date>2017</date>
			<type>tvshow</type>
			<category>News</category>
		</programme>
